### PR TITLE
Draft: Migrate to new sveltekit version

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
- Migrate to the new SvelteKit version
- Don't merge yet please

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Don't deploy this please @vercel lol

**Comment by navneetsharmaui** [comment]
I'm not accepting pull requests for this project right now, as the project is not stable.

**Comment by Explosion-Scratch** [comment]
The idea is that upgrading would make it stable

**Comment by w0rldart** [comment]
@navneetsharmaui @Explosion-Scratch is this initiative scratched now, and this boilerplate obsolete?

**Pull request closed without merging**
